Repository Retro-R-Us/Retro-R-Us, pull requests merged in 2023-01, with the labels that each got.

#23 Users table
  db/client.js
  db/init_db.js
Labels: enhancement

#26 feat: created consoles table closes #5
  db/init_db.js
Labels: enhancement

#27 feat(db table): Implemented db table for cart; Closes #3
  db/init_db.js
Labels: enhancement

#28 feat(DB Tables): Added the SQL query create accessories table closes #6
  db/init_db.js
Labels: enhancement

#29 feat(db table): Implemented db table for orders Closes #4
  db/init_db.js
Labels: enhancement

#35 feat: added collectiblesTable closes #7
  db/init_db.js
Labels: enhancement

#39 Methods orders Closes #21
  db/models/orders.js
Labels: enhancement

#38 feat(DB Games): Implemented games table DB functions
  db/models/games.js
Labels: enhancement

#40 feat: db methods for consoles table closes #32
  db/models/consoles.js
Labels: enhancement

#42 db users methods
  db/init_db.js
  db/models/index.js
  db/models/user.js
  package-lock.json
  package.json
Labels: enhancement

#44 Collectibles db methods closes #34
  db/models/collectibles.js
Labels: enhancement

#46 refactor: moved cart table creation to bottom, avoid drop errors
  db/init_db.js
Labels: Fix

#43 feat(db):Completed updateCart and getOrderById functions
  db/models/cart.js
Labels: enhancement

#47 refactor: createUser if/else, small typo fixes
  db/models/user.js
Labels: Fix

#48 feat: added admin columns to users table
  db/init_db.js
Labels: enhancement

#50 Update init_db.js
  db/init_db.js
Labels: Fix

#51 feat: added model exports
  db/models/index.js
Labels: enhancement

#53 User Routes
  api/PK.js
  api/index.js
  api/user.js
  db/init_db.js
  db/models/user.js
  package-lock.json
  package.json
Labels: enhancement, Fix

#56 User Routes
  api/PK.js
  api/user.js
  index.js
  package-lock.json
  package.json
Labels: enhancement, Fix

#54 feat(api):Developed Cart API
  api/cart.js
  api/index.js
Labels: enhancement

#61 Updated collectibles api closes #18
  api/collectibles.js
  api/consoles.js
  api/index.js
  db/models/collectibles.js
  db/models/consoles.js
Labels: enhancement

#77 Users methods
  api/user.js
  db/init_db.js
  db/models/user.js
Labels: enhancement, Fix

#79 feat: added update method for collectibles db and fixed syntax errors
  api/collectibles.js
  db/models/collectibles.js
Labels: Fix

#78 init_db chores
  db/init_db.js
Labels: Fix

#84 Dbmodels/UserRoute/Init
  api/user.js
  db/init_db.js
  db/models/orders.js
  db/models/user.js
Labels: Fix

#92 feat: updated react, react-dom to @18, react router to @6.6, added sl…
  package-lock.json
  package.json
Labels: enhancement

#94 Init refactor
  db/init_db.js
Labels: Fix

#102 Fe framework
  src/api/accessories.js
  src/api/admin.js
  src/api/cart.js
  src/api/collectibles.js
  src/api/consoles.js
  src/api/games.js
  src/api/index.js
  src/api/orders.js
  src/api/users.js
  src/axios-services/index.js
  src/components/icons/GreenCheck.png
  src/components/icons/RedX.png
Labels: enhancement

#103 Fe framework
  src/api/index.js
  src/components/App.js
Labels: Fix

#104 App
  public/index.html
  src/components/App.js
  src/index.js
  src/style/App.css
Labels: enhancement

#106 Games Component
  src/api/games.js
  src/components/App.js
  src/components/games.js
Labels: enhancement

#107 User auth
  api/user.js
  db/models/user.js
  public/index.html
  src/api/index.js
  src/api/users.js
  src/components/App.js
  src/components/Auth.js
Labels: enhancement

#123 starting header component
  src/components/header.js
Labels: enhancement

#126 User modal
  src/api/users.js
  src/components/App.js
  src/components/Auth.js
  src/components/header.js
  src/style/authModal.css
Labels: enhancement

#130 refactor: dropped orders uE, console log, api status
  src/components/App.js
Labels: Fix

#140 Appchanges
  api/user.js
  src/components/App.js
  src/components/Auth.js
  src/components/UserHeader.js
  src/components/header.js
  src/style/App.css
Labels: enhancement

#142 Acct
  api/user.js
  src/components/App.js
  src/components/account.js
  src/components/accountorders.js
  src/components/acctSettings.js
  src/components/acctedit.js
  src/components/images/account.png
  src/components/images/orders.png
  src/components/images/support.png
  src/components/support.js
  src/style/accountHome.css
Labels: enhancement

#146 refactor: style changes
  src/style/App.css
Labels: Fix

#156 Acctnav
  src/api/users.js
  src/components/App.js
  src/components/account.js
  src/components/acctedit.js
  src/components/home.js
Labels: enhancement, Fix

#158 Acctnav
  api/orders.js
  api/user.js
  src/components/App.js
  src/components/account.js
  src/components/accountorders.js
  src/components/orders.js
Labels: enhancement

#160 feat: added category options menu
  src/components/header.js
Labels: enhancement

#164 Cart fixes
  src/components/AddToCartButton.js
  src/components/App.js
  src/components/Cart.js
  src/components/accessories.js
  src/components/collectibles.js
  src/components/consoles.js
  src/components/games.js
Labels: Fix

#167 refactor: state prop added, pass to cart add button
  src/components/collectibles.js
  src/components/consoles.js
  src/components/games.js
Labels: Fix
